<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ItemManagementService-f592f6b5-a0a4-4f92-8e81-38df7e7fa1aa</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="13.0.0" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore">
        <HintPath>..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.18\ref\net8.0\Microsoft.AspNetCore.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\Commands\Locations\" />
    </ItemGroup>
</Project>
